name: RunAwayFromLaser
version: ${project.version}
main: net.kunmc.lab.runawayfromlaser.RunAwayFromLaser
api-version: 1.17
commands:
  rafl:
    usage: |-
      /rafl createStair <width>
      /rafl setStairInfo <width>
      /rafl start
      /rafl stop
      /rafl pause
      /rafl resume
      /rafl config show
      /rafl config set <configItem> <value>
    permission: op